#!/bin/bash

# Install Python 3
sudo apt-get install python3
if ! [ -x "$(command -v pip3)" ]; then
  sudo apt-get install python3-pip
fi
pip3 install -r requirements.txt

read -p "Do you want to encrypt a file? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
  python3 encrypt.py
else
  echo "Exiting after installation"
  exit 0
fi
